name: CI

on:
  pull_request:
    paths-ignore:
      - "readme.md"
      - ".helix/**"
      - ".vscode/**"
  workflow_dispatch:

env:
  PNPM_VERSION: 10

jobs:
  lint-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install pnpm ${{ env.PNPM_VERSION }}
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: pnpm fmt-check
        run: pnpm fmt-check

      - name: lint & check
        run: pnpm lint && pnpm astro check
